import { createChromeStorageStateHookLocal } from "./storage/index";
import {
  KEY_FONT_SIZES,
  DEFAULT_FONT_SIZES,
  KEY_INCOGNITO_MODE,
  DEFAULT_INCOGNITO_MODE,
  KEY_SHOULD_COLOR_FOR_SUBMITTED_BY,
  DEFAULT_SHOULD_COLOR_FOR_SUBMITTED_BY,
  KEY_HOTKEYS_TOGGLE_SIDEBAR,
  DEFAULT_HOTKEYS_TOGGLE_SIDEBAR,
  KEY_SHOULD_SHOW_SIDEBAR_ON_RESULTS,
  DEFAULT_SHOULD_SHOW_SIDEBAR_ON_RESULTS,
  KEY_SIDEBAR_SQUEEZES_PAGE,
  DEFAULT_SIDEBAR_SQUEEZES_PAGE,
} from "./constants";

const SETTINGS_KEY = "settings";
const INITIAL_VALUE = {
  [KEY_SIDEBAR_SQUEEZES_PAGE]: DEFAULT_SIDEBAR_SQUEEZES_PAGE,
  [KEY_FONT_SIZES]: DEFAULT_FONT_SIZES,
  [KEY_INCOGNITO_MODE]: DEFAULT_INCOGNITO_MODE,
  [KEY_SHOULD_COLOR_FOR_SUBMITTED_BY]: DEFAULT_SHOULD_COLOR_FOR_SUBMITTED_BY,
  [KEY_HOTKEYS_TOGGLE_SIDEBAR]: DEFAULT_HOTKEYS_TOGGLE_SIDEBAR,
  [KEY_SHOULD_SHOW_SIDEBAR_ON_RESULTS]: DEFAULT_SHOULD_SHOW_SIDEBAR_ON_RESULTS,
};

export const useSettingsStore = createChromeStorageStateHookLocal(
  SETTINGS_KEY,
  INITIAL_VALUE
);
